New Visitor class methods for preferred MIME type
getkirby/kirby pull request #2168
Opened 2019-10-03 15:00 UTC by lukasbestle

This is the first set of changes from #2148. Removing the deprecated features requires these changes, so I will send the other two PRs once this one is merged.

2019-10-05 12:24 UTC, distantnative commented
I think it might be fine for this PR, but the removal of lines like

```php
$this->assertTrue($page->hasVisibleChildren());
```

should go into it's own PR to not distract while reading the changes and new implementations.

Also the name of the PR seems off since the main part is around preferred MIME type.

2019-10-05 13:58 UTC, lukasbestle commented
@distantnative It's very difficult to structure those PRs properly. The more we split it up, the longer it takes because I can only create the next PR once the previous one has been merged. Removing the tests for example is required for the next PR that removes the deprecated methods, otherwise the tests won't pass.

2019-10-05 14:12 UTC, distantnative commented
Not sure if I follow your steps correctly:
Why can't we bundle removing 

```php
$this->assertTrue($page->hasVisibleChildren());
```

with removing the actual deprecated methods in one PR? The tests should pass when you remove them in the same PR. And bundling would make it much more sensible to me.

I get that splitting PRs can be annoying for the one working on them - trust me @bastianallgeier has pushed me to it over and over cause I tend to make huge PRs XD But from the perspective of one reviewing a PR it's really confusing to see code changes that don't really belong to the rest of the PR.

2019-10-05 14:22 UTC, lukasbestle commented
Oh, right! I actually meant to do that but it looks like I moved the changes to the wrong branch when splitting the PRs. Will fix that now.

2019-10-07 09:45 UTC, bastianallgeier requested changes

2019-10-07 09:45 UTC, bastianallgeier commented on src/Toolkit/Mime.php
> +    }
I'd like to restructure this a bit. 

```php
public static function matches(string $mime, string $wildcard): bool
{
    return fnmatch($wildcard, $mime, FNM_PATHNAME) === true;
}
```

In my opinion, it fits better to the way we normally handle arguments in such static methods. i.e. see `Mime::isAccepted` or something like `Str::contains`. We always pass the "haystack" first and then the "needle" second. 

```
Mime::matches('text/html', 'text/*');
```

2019-10-07 09:45 UTC, bastianallgeier commented on src/Toolkit/Mime.php
> +    }
The rest is great!

2019-10-07 12:03 UTC, bastianallgeier approved these changes
I just made the changes to the Mime class. The rest is perfect!

2019-10-07 12:03 UTC, merged