Cache blueprint extends
getkirby/kirby pull request #2405
Opened 2020-01-22 09:17 UTC by afbora

## Describe the PR

Blueprint extends are now cached by their name.

However, since the `Blueprint` class is statically called in the tests (_tests/Cms/Blueprints/BlueprintFieldTest.php_), it does not match the data in the cache and the test fails. Should we refactor the test class (BlueprintFieldTest) or the cache system I wrote was faulty 😇 . I'm creating it as a draft because I'm not sure.

## Related issues

- Fixes #2364 

## Ready?

- [ ] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

2020-01-23 20:01 UTC, lukasbestle commented
To be honest, I think we should refactor the loading code to avoid having to keep two separate caches (`$loaded` and `$extends`):

- `Blueprint::find()` should always return the blueprint data, not either the data or the file path string. Basically the case where the file exists in the `blueprints` dir should run `Data::read()` and return the array as well.
- With that simplified, the two only callers of that method I can find (`Blueprint::load()` and `Blueprint::extend()`) can be massively simplified to only care for array data. The `if`s for array vs string are no longer required.
- The existing in-memory caching inside `Blueprint::load()` can then be moved to `Blueprint::find()` so that all loaded blueprint files and mixins are cached in the same `$loaded` cache.

2020-01-23 20:02 UTC, lukasbestle requested changes
To be honest, I think we should refactor the loading code to avoid having to keep two separate caches (`$loaded` and `$extends`):

- `Blueprint::find()` should always return the blueprint data, not either the data or the file path string. Basically the case where the file exists in the `blueprints` dir should run `Data::read()` and return the array as well.
- With that simplified, the two only callers of that method I can find (`Blueprint::load()` and `Blueprint::extend()`) can be massively simplified to only care for array data. The `if`s for array vs string are no longer required.
- The existing in-memory caching inside `Blueprint::load()` can then be moved to `Blueprint::find()` so that all loaded blueprint files and mixins are cached in the same `$loaded` cache.

2020-01-24 15:31 UTC, afbora commented
@lukasbestle I made a few attempts, but even though the panel was working, it started to give a lot of errors in the tests. I think I make a mistake in the data types returned. Can I ask you for help 😇 ? If you want, you can delete this PR and open it yourself. Sorry for not being able to apply the changes 🙏

2020-01-24 15:36 UTC, lukasbestle commented
Feel free to push your current state to this PR and I will take over. :)

2020-01-24 15:47 UTC, afbora commented
Thank you so much. That's it from me 😅

2020-01-24 21:06 UTC, lukasbestle approved these changes

2020-01-24 21:08 UTC, lukasbestle commented
I love it when you can fix bugs by removing more code than adding code. 🎉

2020-01-24 21:16 UTC, afbora commented
@lukasbestle I admire you to simplify and solve problems :heart:

2020-01-25 11:20 UTC, afbora commented
@lukasbestle  I was curious about something, I noticed that while testing cache on the final codes. The cache works great, but when I tried to access a page, I saw 4 different requests for that page. And since each request is independent of each other, the cache process is valid only for that request.

Can we make the cache process more efficient? Like writing ready blueprint props as json to the `/cache` folder 💡 

Is this a minor performance concern? 🤔 

**Requests on page**

1. /api/pages/sandbox?view=panel
2. /api/pages/sandbox/sections/pages?page=1
3. /api/pages/sandbox/sections/main-col-0-fields
4. /api/pages/sandbox/sections/files?page=1

2020-01-25 12:36 UTC, lukasbestle commented
Caching the props to file won't increase performance unfortunately as the operation that uses the most time is loading the blueprints from file, not processing/parsing them. If we would cache the data to a JSON file, we would need to find, open and parse that as well, which wouldn't be any faster.

The only thing we could do is to cache fully extended blueprints, which would increase performance for blueprints with a lot of different extends (fewer separate files to open and parse). However that would substantially increase complexity as the cache would need to be invalidated if any of the blueprint files changes – which needs more code and also takes processing time to check. So I don't think this would be worth it.

2020-01-25 13:02 UTC, afbora commented
I understood properly now, thank you. You are right, even if we write to the cache folder, we will do the same operations on `cache` files instead of `yml` files 👍 OK, the present way is fine 😉

2020-02-07 08:49 UTC, bastianallgeier approved these changes

2020-02-07 08:50 UTC, merged