$field->callback() method
getkirby/kirby pull request #2603
Opened 2020-05-06 11:39 UTC by distantnative

## Describe the PR

Adds `$field->callback(function ($field) {...})`

## Related issues

https://github.com/getkirby/ideas/issues/475

## Ready?

- [x] Added unit tests for fixed bug/feature
- [x] Passing all unit tests
- [x] Fixed code style issues with CS fixer and `composer fix`
- [x] Added in-code documentation (if needed)

2020-05-06 12:56 UTC, lukasbestle requested changes
In the future, please use one commit per change. Cleanup changes (for unrelated parts of the code!) should be in a second commit in the same PR. This way, it's much easier to track down changes later in the commit history (the cleanup changes can be confusing when using `git blame` or when taking a look at a single commit).

2020-05-06 12:56 UTC, lukasbestle commented on tests/Cms/Fields/FieldMethodsTest.php
> +        $this->assertEquals('foo', $result);
New tests should use `$this->assertSame('foo', $result->value());`

2020-05-06 14:18 UTC, lukasbestle approved these changes
Awesome! I have just added the issue reference to the first commit message and added a `@since` marker to the new method. LGTM now. 👍

2020-05-08 11:59 UTC, bastianallgeier approved these changes

2020-05-08 11:59 UTC, merged