Redirects to non-fiber resources
getkirby/kirby pull request #4085
Opened 2022-01-11 14:51 UTC by bastianallgeier

## Describe the PR

When firing a redirect to a non-fiber page in routes, the redirect would lead to non-parseable output and the request would fail. This PR fixes this issue.  

## Release notes

### Fixes

- Fixed redirects in fetch requests to non-fiber resources: https://github.com/getkirby/kirby/issues/4084

## Ready?

- [ ] Unit tests for fixed bug/feature
- [ ] In-code documentation (wherever needed)
- [ ] CI checks pass

## When merging

- [ ] Add to [website docs release checklist](https://github.com/getkirby/getkirby.com/pulls) (if needed)
- [ ] Add changes to release notes draft in Notion

2022-01-11 14:57 UTC, pReya requested changes
`request.url` does not always have the same value as the `Location:` header from a redirect. This will be a different URL in some cases.

Also, this approach will create unnecessary requests, if the backend is not changed (e.g. use a different HTTP status). Because the frontend will follow the redirect (first request, whose result is not being used) and then the browser will load the redirect target a second time, when `window.Location.replace` is being called.

2022-01-11 15:11 UTC, bastianallgeier commented
Not sure I'm able to follow to be honest. 

According to MDN response.url is the final URL after any redirects, so it's pretty perfect for this case: https://developer.mozilla.org/en-US/docs/Web/API/Response/url

2022-01-11 23:23 UTC, pReya commented
> Not sure I'm able to follow to be honest.
> 
> According to MDN response.url is the final URL after any redirects, so it's pretty perfect for this case: [developer.mozilla.org/en-US/docs/Web/API/Response/url](https://developer.mozilla.org/en-US/docs/Web/API/Response/url)

Sorry, I was confused. It works as expected, but it still creates an additional/unnecessary request as described above. But I guess there's no way to prevent that?

2022-01-12 08:35 UTC, bastianallgeier commented
I think it's not possible without it. There are two kind of request types in the Panel. 

1. A regular good old HTTP GET request that would normally return the full document for a view. If a view issues a redirect, that GET request will be redirected just as expected. 

2. A JS fetch request. This fetch request expects proper JSON as result to be able to update the state of the view properly. If the response is a redirect there are two possible results once the redirect is finished: 

a. The result is still a proper Panel view that sends back JSON. The view can be rendered and all is fine. 
b. The result is an HTML page or another resource outside the Panel. In this case, the Panel cannot simply update the Vue app with a new state because it does not receive any usable data. The only other option would be to replace the entire HTML document with the result. But this seems very hacky to me and would only work for plain text or HTML results. Redirects to images or other resources would need to be treated differently. That's why reloading the final destination again seems the most stable choice to me.

2022-01-12 09:16 UTC, rasteiner commented
Actually the resource isn't probably even downloaded (not in its entirety, at least). The promise returned by `fetch` resolves as soon as there are response headers (that's why `response.text()` is another promise), and this code does its `window.location.href = response.url; return false;` immediately after that. Probably if the resource is small it fits into the first chunks and is downloaded, but that isn't really a problem. If the resource is large (and would therefore be a problem) and download is aborted shorty after the redirect.

2022-01-12 21:17 UTC, lukasbestle approved these changes
I think it's a nice and elegant solution. If we wanted to optimize for large files, we could first send a `HEAD` request, but that would bring a huge overhead to every request. And given that 99.9 % of responses are Fiber responses, it would very likely decrease performance overall. This solution covers the edge case and it does so well.

2022-01-13 10:41 UTC, merged