Inherit `style` attribute
getkirby/kirby pull request #6345
Opened 2024-03-14 12:59 UTC by distantnative

Everywhere where we set `inheritAttrs: false`, we need to ensure to manually inherit `class` and `style` attributes then.

2024-03-14 17:00 UTC, distantnative commented
Don't merge while we explore option to remove `inheritAttrs: false` completely

2024-04-09 19:44 UTC, distantnative commented
We will keep `inheritAttrs: false`, so this can be reviewed again.

2024-04-17 07:28 UTC, bastianallgeier requested changes
Just a small change.

2024-04-17 07:28 UTC, bastianallgeier commented on panel/src/components/Forms/Blocks/Block.vue
> +		:style="$attrs.style"
```suggestion
		:style="$attrs.style"
		:tabindex="isDisabled ? null : 0"
```

2024-04-17 07:34 UTC, bastianallgeier approved these changes

2024-04-17 07:35 UTC, bastianallgeier commented
I think we need to move forward after v5 by actively describing, which components should be able to set the style attribute at all. It's a great comporomise like this and I'm happy that we can get rid of inheritAttributes, but it does not make sense either to simply allow it everywhere. I think that's the strength of this approach. We have more control and transparency of what is actually possible.

2024-04-17 07:35 UTC, merged

2024-04-17 07:46 UTC, distantnative commented
@bastianallgeier just for clarification, we can't get rid of inheritAttrs

2024-04-17 08:10 UTC, bastianallgeier commented
I put it the wrong way. I mean we get rid of inheritAttributes: true and avoid injecting unwanted non-valid attributes.